

#dir configs
pickle_dir: /home/ubuntu/datasf-profiler/pickled/
log_dir: /home/ubuntu/datasf-profiler/logs/
#log_dir: /Users/j9/Desktop/work/datasf-profiler/logs/
config_dir: /home/ubuntu/datasf-profiler/configs/
#config_dir: /Users/j9/Desktop/work/datasf-profiler/configs/

pickle_data_dir: /home/ubuntu/datasf-profiler/pickled/datasets/
wkbk_uploads_dir: /home/ubuntu/datasf-profiler/wkbk_uploads/
#inputConfigDir: /Users/j9/Desktop/work/datasf-profiler/configs/

inputConfigDir: /home/ubuntu/datasf-profiler/configs/

mm_dd_json_fn: master_dd_fields.json


#other yaml configs
socrata_client_config_fname: socrata_config.yaml
email_config_file: email_config_server.yaml

#file names
exception_logfile: profiler_logs.txt


#socrata specific configs
row_id_field: row_id
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
isLoaded: isLoaded
datasets_to_load_fn: datasets_to_load.csv
dataset_name_field: Socrata Dataset Name
dataset_src_dir_field:  Dataset_Source_Dir
dataset_src_fn_field: Dataset Source Filename
base_url: data.sfgov.org
job_name: Profile Fields

#other stuff
json_key: updt_fields
app_name: Profile Data Fields
baseUrl: https://data.sfgov.org/resource/

jobs:
  profile_fields:
    job_name: Profile Fields
    app_name: Profile Data Fields
  profile_datasets:
    job_name: Profile Datasets
    app_name: Profile Datasets

dataset_name: Field Profiles

dd:
  master_dd:
    fbf: 8zp7-ik63
    row_id: columnid
  field_type:
    fbf: 8efc-aram
  ds_profiles:
    fbf: w6q6-i3uv
    row_id: datasetid
  field_profiles:
    fbf: ekxv-883u
    row_id: columnid
  asset_inventory:
    fbf: 6u88-vc79

migration_qry_url: https://data.sfgov.org/api/migrations/
webtask_config_fn: webtask_configs.yaml
